debug

diff --git a/.github/workflows/backport.yml b/.github/workflows/backport.yml
--- a/.github/workflows/backport.yml
+++ b/.github/workflows/backport.yml
@@ -3,6 +3,9 @@ name: Rebase pre-dev branches
 on:
   workflow_dispatch:
 
+env:
+  OVERALL: success
+
 jobs:
   rebase:
     runs-on: ubuntu-latest
@@ -32,10 +35,16 @@ jobs:
           git push origin ${{ matrix.branch }} --force-with-lease
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Handle rebase conflicts
+        if: failure()
+        run: |
+          echo "OVERALL=failure" >> $GITHUB_ENV
+          exit 1
+  
   check-failures:
     runs-on: ubuntu-latest
     needs: rebase
-    if: always()
     steps:
       - name: Conditional exiting
-        run: echo ${{ needs.rebase.result }}
+        run: '[ "$OVERALL" = "failure" ] && exit 1'
